### ISSUE TITLE
Remote Client Issue

### ISSUE THREAD

**Issue by kirillkazakov** [CMPUT301W17T06/MoodBook#41]
Remote Client works sometimes, but with laptops not always. Here is the stuff I am getting from the console when it is complaining.

W/System.err: java.net.UnknownHostException: Unable to resolve host "cmput301.softwareprocess.es": No address associated with hostname
W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:752)
W/System.err:     at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
W/System.err:     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:102)
W/System.err:     at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:322)
W/System.err:     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:373)
W/System.err:     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:225)
W/System.err:     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
W/System.err:     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
W/System.err:     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
W/System.err:     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:178)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
W/System.err:     at com.searchly.jestdroid.JestDroidClient.execute(JestDroidClient.java:51)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient.setupIndex(RemoteClient.java:106)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient.setupOnline(RemoteClient.java:94)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient.verifyConfig(RemoteClient.java:64)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll.doInBackground(RemoteClient.java:362)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll.doInBackground(RemoteClient.java:351)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
W/System.err: java.net.UnknownHostException: Unable to resolve host "cmput301.softwareprocess.es": No address associated with hostname
W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:752)
W/System.err:     at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
W/System.err:     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:102)
W/System.err:     at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:322)
W/System.err:     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:373)
W/System.err:     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:225)
W/System.err:     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
W/System.err:     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
W/System.err:     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
W/System.err:     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:178)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
W/System.err:     at com.searchly.jestdroid.JestDroidClient.execute(JestDroidClient.java:51)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll.doInBackground(RemoteClient.java:378)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll.doInBackground(RemoteClient.java:351)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
I/RemoteClient: setting cache forcom.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll
I/RemoteClient: Running all queued tasks
I/RemoteClient: checking cache for com.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll
E/RemoteClient: cached value was invalid
W/System.err: java.net.UnknownHostException: Unable to resolve host "cmput301.softwareprocess.es": No address associated with hostname
W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:752)
W/System.err:     at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
W/System.err:     at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:102)
W/System.err:     at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:322)
W/System.err:     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:373)
W/System.err:     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:225)
W/System.err:     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
W/System.err:     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
W/System.err:     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
W/System.err:     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:178)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
W/System.err:     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
W/System.err:     at com.searchly.jestdroid.JestDroidClient.execute(JestDroidClient.java:51)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient.setupIndex(RemoteClient.java:106)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient.setupOnline(RemoteClient.java:94)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient.verifyConfig(RemoteClient.java:64)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll.doInBackground(RemoteClient.java:362)
W/System.err:     at com.cmput301.cmput301w127t06.moodbook.RemoteClient$SearchAll.doInBackground(RemoteClient.java:351)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by Everlag** [comment]
`Unable to resolve host "cmput301.softwareprocess.es": No address associated with hostname`

That looks like a emulator problem, not something I can really deal with. Is the wifi being iffy or something?

**Comment by ZackerySpytz** [comment]
I also get these errors frequently when working at home. I believe it may be an issue with the emulator's wifi connection.

**Comment by Everlag** [comment]
I'm going to say this is likely caused by the emulator losing connection when the host is sleeping/hibernating. If restarting the emulator doesn't fix this, reopen this issue and yell at me.
